import Footer from "@/components/footer/footer";
import Header from "@/components/header/header";
import type { Metadata } from "next";
import { Inter, JetBrains_Mono, Space_Grotesk } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space-grotesk",
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains-mono",
  weight: ["400", "500", "600"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script
          id="goatcounter"
          strategy="afterInteractive"
          data-goatcounter="https://napsryu.goatcounter.com/count"
          src="//gc.zgo.at/count.js"
          async
        />
        <link rel="icon" href="/favicon.svg" />
      </head>
      <body
        className={`${spaceGrotesk.variable} ${inter.variable} ${jetbrainsMono.variable}`}
      >
        {/* Background layers */}
        <div className="bg-layer bg-base" />
        <div className="bg-layer bg-grid" />
        <div className="bg-layer bg-aurora">
          <div className="aurora aurora--violet" />
          <div className="aurora aurora--indigo" />
          <div className="aurora aurora--cyan" />
        </div>
        <div className="bg-layer bg-grain" />
        <div className="bg-layer bg-vignette" />

        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
