import { Project } from "@/models/project.model";

export const allProjects: Project[] = [
  {
    homepage: true,
    id: "NUw5jIAVSrieCJRpXsvRcA",
    preview: {
      url: "/cms/oakbot-preview.webp",
      title: "oakbot-preview",
      alt: "oakbot-preview",
    },
    skill: ["Telegram", "NodeJS"],
    slug: "oakbot",
    subtitle: "🧠 A Smart Pokédex, Right in Your Telegram",
    title: "OakBot",
    urlGithub: "https://github.com/gNaps/pokedex-bot",
    urlPreview: "https://t.me/napsryu_pokedex_bot",
  },
  {
    homepage: true,
    id: "qTs3DprETD2qjh_DcpQDEg",
    preview: {
      url: "/cms/regalando.webp",
      title: "regalando",
      alt: "regalando",
    },
    skill: ["Flutter", "NextJS", "Supabase"],
    slug: "regalando",
    subtitle: "🎁 The Gift-Giving Experience, Reimagined",
    title: "Regalando",
    urlGithub: "https://github.com/gNaps/regalando-web",
    urlPreview: "www.regalando.vercel.app",
  },
  {
    homepage: true,
    id: "2rBjHTtsTEa5muhRB7tOnA",
    preview: {
      url: "/cms/tmanager.webp",
      title: "tamager",
      alt: "tamager",
    },
    skill: ["Angular", "Fastify", "Prisma", "PostgreSQL"],
    slug: "tmanager",
    subtitle: "⚽ Managing Team Travel, Made Effortless",
    title: "TManager",
    urlGithub: "",
    urlPreview: "https://www.tmanager.it",
  },
  {
    homepage: false,
    id: "JceLtZRkRd2u2gLnzbq7UQ",
    preview: {
      url: "/cms/magic_link.webp",
      title: "magic-link",
      alt: "magic-link",
    },
    skill: ["NodeJS"],
    slug: "magic-link",
    subtitle: "Passwordless Authentication, Simplified",
    title: "Magic Link",
    urlGithub: "https://github.com/gNaps/magic-link-prisma",
    urlPreview: "",
  },
  {
    homepage: false,
    id: "NF2-XZyZQDOleA7O1g58jQ",
    preview: {
      url: "/cms/lick_nft.webp",
      title: "lick-nft",
      alt: "lick-nft",
    },
    skill: ["NextJS", "Ethereum"],
    slug: "licks-nft",
    subtitle: "Generator of musical NFT",
    title: "Licks NFT",
    urlGithub: "https://github.com/gNaps/Chainlink-Random-Licks",
    urlPreview: "https://vercel.com/gnaps/chainlink-random-licks",
  },
  {
    homepage: false,
    id: "QUvavDRdQOuXRdj6yV-VcA",
    preview: {
      url: "/cms/pokerdle.webp",
      title: "pokerdle",
      alt: "pokerdle",
    },
    skill: ["NextJS"],
    slug: "pokerdle",
    subtitle: "A Wordle based game about Pokemon",
    title: "Pokerdle",
    urlGithub: "https://github.com/gNaps/pokerdle",
    urlPreview: "https://pokerdle.vercel.app/",
  },
  {
    homepage: true,
    id: "KfEA1kq1RP6EoBn6hDCR6A",
    preview: {
      url: "/cms/angular_dashboard.webp",
      title: "angular-dashboard",
      alt: "angular-dashboard",
    },
    skill: ["Angular"],
    slug: "dashboard-template",
    subtitle: "Angular dashboard starter template",
    title: "Dashboard Template",
    urlGithub: "https://github.com/gNaps/angular-dashboard-template",
    urlPreview: "",
  },
];
