import { Story } from "@/models/story.model";

export const allStories: Story[] = [
  {
    slug: "come-un-llm-sceglie-le-parole",
    homepage: true,
    id: 39,
    title: "Come fa un LLM a scegliere le parole?",
    writtenAt: "2026-08-02",
    preview: {
      url: "",
      title: "come-un-llm-sceglie-le-parole",
      alt: "Come fa un LLM a scegliere le parole",
    },
  },
  {
    slug: "llm-chatbot-agenti-chi-fa-cosa",
    homepage: true,
    id: 38,
    title: "LLM, chatbot, agenti: chi fa cosa",
    writtenAt: "2026-08-02",
    preview: {
      url: "",
      title: "llm-chatbot-agenti-chi-fa-cosa",
      alt: "LLM, chatbot, agenti: chi fa cosa",
    },
  },
  {
    slug: "vibe-coding-vs-spec-driven-development",
    homepage: true,
    id: 37,
    title: "Vibe coding vs spec-driven development",
    writtenAt: "2026-08-02",
    preview: {
      url: "",
      title: "vibe-coding-vs-spec-driven-development",
      alt: "Vibe coding vs spec-driven development",
    },
  },
  {
    slug: "galactic-guide-to-web-developing/sviluppo-web-da-zero/best-practice/step-3",
    homepage: false,
    id: 36,
    title: "Come continuare a imparare",
    writtenAt: "2026-08-01",
    preview: {
      url: "",
      title: "sviluppo-web-da-zero-24",
      alt: "Sviluppo web da zero - come continuare a imparare",
    },
  },
  {
    slug: "galactic-guide-to-web-developing/sviluppo-web-da-zero/best-practice/step-2",
    homepage: false,
    id: 35,
    title: "Controllo versione con Git",
    writtenAt: "2026-08-01",
    preview: {
      url: "",
      title: "sviluppo-web-da-zero-23",
      alt: "Sviluppo web da zero - controllo versione con Git",
    },
  },
  {
    slug: "galactic-guide-to-web-developing/sviluppo-web-da-zero/best-practice/step-1",
    homepage: false,
    id: 34,
    title: "Organizzare un progetto web",
    writtenAt: "2026-08-01",
    preview: {
      url: "",
      title: "sviluppo-web-da-zero-22",
      alt: "Sviluppo web da zero - organizzare un progetto web",
    },
  },
  {
    slug: "galactic-guide-to-web-developing/sviluppo-web-da-zero/il-ciclo-completo/step-2",
    homepage: false,
    id: 33,
    title: "Il flusso completo, dal click al pixel",
    writtenAt: "2026-08-01",
    preview: {
      url: "",
      title: "sviluppo-web-da-zero-21",
      alt: "Sviluppo web da zero - il flusso completo dal click al pixel",
    },
  },
  {
    slug: "galactic-guide-to-web-developing/sviluppo-web-da-zero/il-ciclo-completo/step-1",
    homepage: false,
    id: 32,
    title: "Come comunicano frontend e backend",
    writtenAt: "2026-08-01",
    preview: {
      url: "",
      title: "sviluppo-web-da-zero-20",
      alt: "Sviluppo web da zero - come comunicano frontend e backend",
    },
  },
  {
    slug: "galactic-guide-to-web-developing/sviluppo-web-da-zero/i-database/step-4",
    homepage: false,
    id: 31,
    title: "Collegare un'app al database",
    writtenAt: "2026-08-01",
    preview: {
      url: "",
      title: "sviluppo-web-da-zero-19",
      alt: "Sviluppo web da zero - collegare un'app al database",
    },
  },
  {
    slug: "galactic-guide-to-web-developing/sviluppo-web-da-zero/i-database/step-3",
    homepage: false,
    id: 30,
    title: "Query SQL di base",
    writtenAt: "2026-08-01",
    preview: {
      url: "",
      title: "sviluppo-web-da-zero-18",
      alt: "Sviluppo web da zero - query SQL di base",
    },
  },
  {
    slug: "galactic-guide-to-web-developing/sviluppo-web-da-zero/i-database/step-2",
    homepage: false,
    id: 29,
    title: "Concetti base dei database relazionali",
    writtenAt: "2026-08-01",
    preview: {
      url: "",
      title: "sviluppo-web-da-zero-17",
      alt: "Sviluppo web da zero - concetti base dei database relazionali",
    },
  },
  {
    slug: "galactic-guide-to-web-developing/sviluppo-web-da-zero/i-database/step-1",
    homepage: false,
    id: 28,
    title: "Cos'è un database e perché è importante",
    writtenAt: "2026-08-01",
    preview: {
      url: "",
      title: "sviluppo-web-da-zero-16",
      alt: "Sviluppo web da zero - cos'è un database e perché è importante",
    },
  },
  {
    slug: "galactic-guide-to-web-developing/sviluppo-web-da-zero/il-backend/step-6",
    homepage: false,
    id: 27,
    title: "Sicurezza essenziale: mai fidarsi di nessuno",
    writtenAt: "2026-08-01",
    preview: {
      url: "",
      title: "sviluppo-web-da-zero-15",
      alt: "Sviluppo web da zero - sicurezza essenziale",
    },
  },
  {
    slug: "galactic-guide-to-web-developing/sviluppo-web-da-zero/il-backend/step-5",
    homepage: false,
    id: 26,
    title: "Il primo backend vero: le API dei Guardiani",
    writtenAt: "2026-08-01",
    preview: {
      url: "",
      title: "sviluppo-web-da-zero-14",
      alt: "Sviluppo web da zero - il primo backend vero con Fastify",
    },
  },
  {
    slug: "galactic-guide-to-web-developing/sviluppo-web-da-zero/il-backend/step-4",
    homepage: false,
    id: 25,
    title: "Node.js: JavaScript fuori dal browser",
    writtenAt: "2026-08-01",
    preview: {
      url: "",
      title: "sviluppo-web-da-zero-13",
      alt: "Sviluppo web da zero - Node.js: JavaScript fuori dal browser",
    },
  },
  {
    slug: "galactic-guide-to-web-developing/sviluppo-web-da-zero/il-backend/step-3",
    homepage: false,
    id: 23,
    title: "Il concetto di CRUD",
    writtenAt: "2026-08-01",
    preview: {
      url: "",
      title: "sviluppo-web-da-zero-12",
      alt: "Sviluppo web da zero - il concetto di CRUD",
    },
  },
  {
    slug: "galactic-guide-to-web-developing/sviluppo-web-da-zero/il-backend/step-2",
    homepage: false,
    id: 24,
    title: "HTTP e il protocollo client-server",
    writtenAt: "2026-08-01",
    preview: {
      url: "",
      title: "sviluppo-web-da-zero-11",
      alt: "Sviluppo web da zero - HTTP e il protocollo client-server",
    },
  },
  {
    slug: "galactic-guide-to-web-developing/sviluppo-web-da-zero/il-backend/step-1",
    homepage: false,
    id: 22,
    title: "Cos'è il backend e cosa fa",
    writtenAt: "2026-08-01",
    preview: {
      url: "",
      title: "sviluppo-web-da-zero-10",
      alt: "Sviluppo web da zero - cos'è il backend e cosa fa",
    },
  },
  {
    slug: "galactic-guide-to-web-developing/sviluppo-web-da-zero/il-frontend/step-6",
    homepage: false,
    id: 21,
    title: "Framework e librerie: perché esistono e come sceglierli",
    writtenAt: "2026-08-01",
    preview: {
      url: "",
      title: "sviluppo-web-da-zero-9",
      alt: "Sviluppo web da zero - framework e librerie moderne",
    },
  },
  {
    slug: "galactic-guide-to-web-developing/sviluppo-web-da-zero/il-frontend/step-5",
    homepage: false,
    id: 20,
    title: "JavaScript: la logica nel browser",
    writtenAt: "2026-08-01",
    preview: {
      url: "",
      title: "sviluppo-web-da-zero-8",
      alt: "Sviluppo web da zero - JavaScript: la logica nel browser",
    },
  },
  {
    slug: "galactic-guide-to-web-developing/sviluppo-web-da-zero/il-frontend/step-4",
    homepage: false,
    id: 19,
    title: "CSS: lo stile dell'interfaccia",
    writtenAt: "2026-08-01",
    preview: {
      url: "",
      title: "sviluppo-web-da-zero-7",
      alt: "Sviluppo web da zero - CSS: lo stile dell'interfaccia",
    },
  },
  {
    slug: "galactic-guide-to-web-developing/sviluppo-web-da-zero/il-frontend/step-3",
    homepage: false,
    id: 18,
    title: "HTML: la struttura della pagina",
    writtenAt: "2026-08-01",
    preview: {
      url: "",
      title: "sviluppo-web-da-zero-6",
      alt: "Sviluppo web da zero - HTML: la struttura della pagina",
    },
  },
  {
    slug: "galactic-guide-to-web-developing/sviluppo-web-da-zero/il-frontend/step-2",
    homepage: false,
    id: 17,
    title: "Il browser: il nostro interprete",
    writtenAt: "2026-08-01",
    preview: {
      url: "",
      title: "sviluppo-web-da-zero-5",
      alt: "Sviluppo web da zero - il browser: il nostro interprete",
    },
  },
  {
    slug: "galactic-guide-to-web-developing/sviluppo-web-da-zero/il-frontend/step-1",
    homepage: false,
    id: 16,
    title: "Cos'è il frontend e cosa fa",
    writtenAt: "2026-08-01",
    preview: {
      url: "",
      title: "sviluppo-web-da-zero-4",
      alt: "Sviluppo web da zero - cos'è il frontend e cosa fa",
    },
  },
  {
    slug: "galactic-guide-to-web-developing/sviluppo-web-da-zero/introduzione-allo-sviluppo-web/step-3",
    homepage: false,
    id: 15,
    title: "Gli strumenti del mestiere",
    writtenAt: "2026-08-01",
    preview: {
      url: "",
      title: "sviluppo-web-da-zero-3",
      alt: "Sviluppo web da zero - gli strumenti del mestiere",
    },
  },
  {
    slug: "galactic-guide-to-web-developing/sviluppo-web-da-zero/introduzione-allo-sviluppo-web/step-2",
    homepage: false,
    id: 14,
    title: "Come funziona una web app moderna",
    writtenAt: "2026-08-01",
    preview: {
      url: "",
      title: "sviluppo-web-da-zero-2",
      alt: "Sviluppo web da zero - come funziona una web app moderna",
    },
  },
  {
    slug: "galactic-guide-to-web-developing/sviluppo-web-da-zero/introduzione-allo-sviluppo-web/step-1",
    homepage: false,
    id: 13,
    title: "Cos'è lo sviluppo web?",
    writtenAt: "2026-08-01",
    preview: {
      url: "",
      title: "sviluppo-web-da-zero-1",
      alt: "Sviluppo web da zero - cos'è lo sviluppo web",
    },
  },
  {
    slug: "galactic-guide-to-web-developing/angular-in-10-steps/step-10",
    homepage: true,
    id: 12,
    title: "Angular in 10 steps - 10 of 10",
    writtenAt: "2026-08-01",
    preview: {
      url: "/cms/angular_in_10_steps.webp",
      title: "angular_in_10_steps_10_10",
      alt: "angular in 10 steps 10 of 10",
    },
  },
  {
    slug: "galactic-guide-to-web-developing/angular-in-10-steps/step-9",
    homepage: true,
    id: 11,
    title: "Angular in 10 steps - 9 of 10",
    writtenAt: "2026-08-01",
    preview: {
      url: "/cms/angular_in_10_steps.webp",
      title: "angular_in_10_steps_9_10",
      alt: "angular in 10 steps 9 of 10",
    },
  },
  {
    slug: "galactic-guide-to-web-developing/angular-in-10-steps/step-8",
    homepage: true,
    id: 10,
    title: "Angular in 10 steps - 8 of 10",
    writtenAt: "2026-08-01",
    preview: {
      url: "/cms/angular_in_10_steps.webp",
      title: "angular_in_10_steps_8_10",
      alt: "angular in 10 steps 8 of 10",
    },
  },
  {
    slug: "galactic-guide-to-web-developing/angular-in-10-steps/step-7",
    homepage: true,
    id: 9,
    title: "Angular in 10 steps - 7 of 10",
    writtenAt: "2026-08-01",
    preview: {
      url: "/cms/angular_in_10_steps.webp",
      title: "angular_in_10_steps_7_10",
      alt: "angular in 10 steps 7 of 10",
    },
  },
  {
    slug: "galactic-guide-to-web-developing/angular-in-10-steps/step-6",
    homepage: true,
    id: 8,
    title: "Angular in 10 steps - 6 of 10",
    writtenAt: "2026-08-01",
    preview: {
      url: "/cms/angular_in_10_steps.webp",
      title: "angular_in_10_steps_6_10",
      alt: "angular in 10 steps 6 of 10",
    },
  },
  {
    slug: "galactic-guide-to-web-developing/angular-in-10-steps/step-5",
    homepage: true,
    id: 7,
    title: "Angular in 10 steps - 5 of 10",
    writtenAt: "2026-08-01",
    preview: {
      url: "/cms/angular_in_10_steps.webp",
      title: "angular_in_10_steps_5_10",
      alt: "angular in 10 steps 5 of 10",
    },
  },
  {
    slug: "galactic-guide-to-web-developing/angular-in-10-steps/step-4",
    homepage: true,
    id: 6,
    title: "Angular in 10 steps - 4 of 10",
    writtenAt: "2026-08-01",
    preview: {
      url: "/cms/angular_in_10_steps.webp",
      title: "angular_in_10_steps_4_10",
      alt: "angular in 10 steps 4 of 10",
    },
  },
  {
    slug: "galactic-guide-to-web-developing/angular-in-10-steps/step-3",
    homepage: true,
    id: 5,
    title: "Angular in 10 steps - 3 of 10",
    writtenAt: "2026-08-01",
    preview: {
      url: "/cms/angular_in_10_steps.webp",
      title: "angular_in_10_steps_3_10",
      alt: "angular in 10 steps 3 of 10",
    },
  },
  {
    slug: "galactic-guide-to-web-developing/angular-in-10-steps/step-2",
    homepage: true,
    id: 4,
    title: "Angular in 10 steps - 2 of 10",
    writtenAt: "2025-07-20",
    preview: {
      url: "/cms/angular_in_10_steps.webp",
      title: "angular_in_10_steps_2_10",
      alt: "angular in 10 steps 2 of 10",
    },
  },
  {
    slug: "galactic-guide-to-web-developing/angular-in-10-steps/step-1",
    homepage: true,
    id: 3,
    title: "Angular in 10 steps - 1 of 10",
    writtenAt: "2025-07-13",
    preview: {
      url: "/cms/angular_in_10_steps.webp",
      title: "angular_in_10_steps_1_10",
      alt: "angular in 10 steps 1 of 10",
    },
  },
  {
    slug: "nextjs-twitch-authentication",
    homepage: true,
    id: 2,
    title: "Login con Twitch in Next.js e Auth.js",
    writtenAt: "2023-08-25",
    preview: {
      url: "/cms/nextjs-twitch-authentication.webp",
      title: "nextjs-twitch-authentication",
      alt: "nextjs twitch authentication",
    },
  },
  {
    slug: "rxjs-zip-vs-combinelatest-vs-withlatestfrom-vs-forkjoin",
    homepage: true,
    id: 1,
    title: "RxJS: zip vs combineLatest vs withLatestFrom vs forkJoin",
    writtenAt: "2023-11-08",
    preview: {
      url: "/cms/rxjs-zip-vs-combinelast-vs-withlatestfrom-vs-forkjoin.webp",
      title: "rxjs-zip-vs-combinelatest-vs-withlatestfrom-vs-forkjoin",
      alt: "rxjs zip vs combinelatest vs withlatestfrom vs forkjoin",
    },
  },
];
